name: Visual Regression Testing (VRT)

on:
  pull_request:
    branches:
      - main # mainブランチへのプルリクエストが来たときに実行

jobs:
  vrt:
    runs-on: ubuntu-latest

    steps:
      # 1. リポジトリをチェックアウト
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Node.js をセットアップ
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18 # 必要なNode.jsのバージョンを指定

      # 3. 必要な依存関係をインストール
      - name: Install dependencies
        run: npm install

      # 4. VRTを実行
      - name: Run Visual Regression Testing
        id: run-vrt
        run: npm run compare | tee vrt-output.txt

      # 5. 差分レポートをアーティファクトとして保存（オプション）
      - name: Extract VRT results
        id: extract-results
        run: |
          changed=$(grep 'Changed items:' vrt-output.txt | awk '{print $3}')
          new=$(grep 'New items:' vrt-output.txt | awk '{print $3}')
          deleted=$(grep 'Deleted items:' vrt-output.txt | awk '{print $3}')
          passed=$(grep 'Passed items:' vrt-output.txt | awk '{print $3}')
          echo "::set-output name=changed::$changed"
          echo "::set-output name=new::$new"
          echo "::set-output name=deleted::$deleted"
          echo "::set-output name=passed::$passed"

      # 6. 差分がある場合にマージをブロック
      - name: Block merge if there are changes
        if: ${{ steps.extract-results.outputs.changed > 0 }}
        run: exit 1
