name: Visual Regression Testing (VRT)

on:
  pull_request:
    branches:
      - main # mainブランチへのプルリクエストが来たときに実行

jobs:
  vrt:
    runs-on: ubuntu-latest

    steps:
      # 1. リポジトリをチェックアウト
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Node.js をセットアップ
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18 # 必要なNode.jsのバージョンを指定

      # 3. 必要な依存関係をインストール
      - name: Install dependencies
        run: npm install

      # 4. VRTを実行
      - name: Run Visual Regression Testing
        id: run-vrt
        run: npm run compare | tee vrt-output.txt

      # 5. Changed itemsの数をチェックし、1以上なら失敗
      - name: Check for changes
        run: |
          CHANGED_ITEMS=$(grep -oP '(?<=Changed items: )\d+' vrt-output.txt)
          if [ "$CHANGED_ITEMS" -ge 1 ]; then
            echo "Visual regression test failed: $CHANGED_ITEMS changed items found."
            exit 1
          fi
