name: Visual Regression Testing (VRT)

on:
  push:
    branches:
      - main  # mainブランチにプッシュされたときに実行

jobs:
  vrt:
    runs-on: ubuntu-latest

    steps:
      # 1. リポジトリをチェックアウト
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Node.js をセットアップ
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18  # 必要なNode.jsのバージョンを指定

      # 3. 必要な依存関係をインストール
      - name: Install dependencies
        run: npm install

      # 4. VRTを実行
      - name: Run Visual Regression Testing
        run: npm run compare

      # 5. 差分レポートをアーティファクトとして保存（オプション）
      - name: Upload report artifacts
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: vrt-report
          path: .regs/out/  # レポートが保存されるパス（必要に応じて変更）
